version: '2'

services:
    openrobertalab_embedded:
        image: rbudde/openrobertalabembedded:${VERSION}
        ports:
            - "7100:1999"
        volumes:
            - "${DB_PARENTDIR}:/opt/db"
        stop_signal: SIGINT
